### ISSUE TITLE
R session Aborted

### ISSUE THREAD

**Issue by cyndyfem** [SantanderMetGroup/loadeR.2nc#2]
Hi,
Thanks for this wonderful tool.
I had reported an error earlier. That was tried on ubuntu 20.04.
However, since I could not solve it. I have proceeded to R on windows to try whether I will be able to solve the problem. Unfortunately, instead of solving it, the R session is always aborted when I used the grid2nc function.
Please, how do I now write out my output from the climate4R grid into .nc after bias-correction?

Thanks!

**Comment by 0-milan-0** [comment]
Hi, I am facing the same issue as you have already mentioned. That is, Rstudio is not producing any output, but processing keeps happening and R has to be manually interrupted to stop it when trying to convert the C4R grid to ncfile using the grid2nc command.
Can you please share any fix you might have already found.

Thanks.
